[opener]
edit = [ { run = 'nvim "$@"', block = true, for = 'unix'} ]
open = [ { run = 'xdg-open "$@"', for = 'unix' } ]
play = [ { run = 'mpv "$@"', for = 'unix' } ]

[open]
rules = [
  { mime = 'text/*', use = 'edit' },
  { mime = 'image/*', use = 'open' },
  { mime = '{audio, video}/*', use = 'play' }
]
