[opener]
edit = [ { run = 'nvim "$@"', block = true, for = 'unix'} ]
view = [ { run = 'imv-dir "$@"', for = 'unix' } ]
play = [ { run = 'mpv "$@"', for = 'unix' } ]

[open]
rules = [
  { mime = 'text/*', use = 'edit' },
  { mime = 'image/*', use = 'view' },
  { mime = '{audio, video}/*', use = 'play' }
]

[tasks]
image_bound = [ 0, 0 ]
