# MODULES
# The following modules are loaded before any boot hooks are run.
MODULES=()

# BINARIES
BINARIES=()

# FILES
FILES=(/lib/firmware/amdgpu/oland_ce.bin /lib/firmware/amdgpu/oland_k_smc.bin /lib/firmware/amdgpu/oland_mc.bin /lib/firmware/amdgpu/oland_me.bin /lib/firmware/amdgpu/oland_pfp.bin /lib/firmware/amdgpu/oland_rlc.bin /lib/firmware/amdgpu/oland_smc.bin /lib/firmware/amdgpu/oland_uvd.bin)

# HOOKS
HOOKS=(base udev autodetect microcode modconf kms block filesystems fsck)

# COMPRESSION
COMPRESSION="lz4"

# COMPRESSION_OPTIONS
#COMPRESSION_OPTIONS=()

# MODULES_DECOMPRESS
MODULES_DECOMPRESS="no"
